server:
  port: 8080
spring:
  application:
    name: cloud-order-service
eureka:
  #instance:
    #prefer-ip-address: true #使用ip地址注册
    #instance-id: cloud-order-service
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
     # defaultZone: http://localhost:7001/eureka #单机版本
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本



